version: "3.5"

services:

  #php server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ../canvas-core:/canvas-core
      - ../baka:/baka
    depends_on: 
      - 'mysql'
      - 'rabbitmq'
    tty: true
    ports:
      - "9000:9000"
    networks:
      - local-network

  mysql:
    image: mariadb:10.4
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - '.env'
    volumes:
      - "db-data:/var/lib/mysql"
      - "./storage/ci/mysql.cnf:/etc/mysql/conf.d/kanvas.cnf"
    networks:
        - local-network

  rabbitmq:
    image: rabbitmq:3.7.16-management
    hostname: "rabbitmq"
    env_file:
      - '.env'
    labels:
      NAME: "rabbitmq"
    volumes:
      - "rabbitsvolumns:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - local-network

volumes:
  db-data:
  rabbitsvolumns:

networks:
  local-network:
  public-network:
